// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6kZgyay4JAvDf5XuvKgUsgAj2UweivOM',
    appId: '1:532321097774:web:5078ab15ea7a948e0fa7bf',
    messagingSenderId: '532321097774',
    projectId: 'amethyst-sos',
    authDomain: 'amethyst-sos.firebaseapp.com',
    storageBucket: 'amethyst-sos.appspot.com',
    measurementId: 'G-DLCCNS4X13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_0gHdrZZnKNuaqqH0fQ6LB3b6c9R78i4',
    appId: '1:532321097774:android:eb291aa689cae5520fa7bf',
    messagingSenderId: '532321097774',
    projectId: 'amethyst-sos',
    storageBucket: 'amethyst-sos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK-jTsbmnUJ1vSZ6Pc3pfpaQGiuvdUwKE',
    appId: '1:532321097774:ios:45cdbeec71d8d8a90fa7bf',
    messagingSenderId: '532321097774',
    projectId: 'amethyst-sos',
    storageBucket: 'amethyst-sos.appspot.com',
    iosClientId: '532321097774-uidtvhn2s05vlmqb53g73vs72tj5eq6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.vistasAmatista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK-jTsbmnUJ1vSZ6Pc3pfpaQGiuvdUwKE',
    appId: '1:532321097774:ios:af36f51e063fce710fa7bf',
    messagingSenderId: '532321097774',
    projectId: 'amethyst-sos',
    storageBucket: 'amethyst-sos.appspot.com',
    iosClientId: '532321097774-1bgdlhtpt5f7v2hva6ucnbcg9imv9vq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.vistasAmatista.RunnerTests',
  );
}
